const express=require("express");
const dotenv=require("dotenv");
const cors=require("cors");
const connectDB=require("./config/db");
const authRoute=require("./routes/authRoutes");
const jobRoute=require("./routes/jobRoutes");
const adminRoutes = require("./routes/adminRoutes");
dotenv.config();
connectDB();
const app=express();
app.use(cors());
app.use(express.json());
app.use("/api/auth",authRoute);
app.use("/api/jobs",jobRoute);
app.use("/api/admin", require("./routes/adminRoutes"));
app.use("/uploads",express.static("uploads"));
const PORT=process.env.PORT||4000;
app.get("/", (req, res) => {
  res.send("Job Portal API is running...");
});
app.listen(PORT,()=>console.log(`Server running on port ${PORT}`));