const mongoose=require("mongoose");
const jobSchema=new mongoose.Schema(
  {
    title:{
      type:String,
      required:true,
    },
    description:{
      type:String,
      required:true,
    },
    location:{
      type:String,
      required:true,
    },
    salary:{
      type:String,
    },
    jobType:{
      type:String,
      enum:["Full-time","Part-time","Internship"],
      default:"Full-time",
    },
    employer:{
      type:mongoose.Schema.Types.ObjectId,
      ref:"User",
      required:true
    },
    isActive:{
      type:Boolean,
      default:true,
    },
  },
  {timestamps:true}
);
module.exports=mongoose.model("Job",jobSchema);